[tool.poetry]
name = "cjclub"
version = "0.1.0"
description = ""
authors = ["patarapolw <polv@polv.cc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.88.0"
regex = "^2022.10.31"
wordfreq = "^3.0.3"
jieba = "^0.42.1"
uvicorn = "^0.20.0"
mecab-python3 = "^1.0.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
