[tool.poetry]
name = "tts-server"
version = "0.1.0"
description = ""
authors = ["patarapolw <polv@polv.cc>"]

[tool.poetry.dependencies]
python = "^3.8"
gTTS = "^2.2.2"
fastapi = "^0.63.0"
uvicorn = "^0.13.4"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
